projects:
  # maya_vr:
  #   name: Maya VR
  #   latex: project_maya
  #   branch: maya_vr
  #   assignees:
  #     - AviralAgrwal
  mangrove_monitoring:
    name: Mangrove Monitoring
    latex: project_mm
    branch: mangrove_monitoring
    assignees:
      - gagewrye
      - TWintersww
  acoustic_species_id:
    name: Acoustic Species ID
    latex: project_aid
    branch: acoustic_species_id
    assignees:
      - Sean1572
      - SiyaKamboj
      - Ludwigvsch
      - tqzhang04
  acoustic_collar:
    name: Acoustic Collar
    latex: project_aid_collar
    branch: acoustic_collar
    assignees:
      - Ludwigvsch
      - zclawr
  baboons_on_the_move:
    name: Baboons on the Move
    latex: project_bom
    branch: baboons_on_the_move
    assignees:
      - ccrutchf
      - TylerFlar
  fs_lite:
    name: FishSense Lite
    latex: project_fs_lite
    branch: fs_lite
    assignees:
      - ccrutchf
      - Shuzhengz
  fs_mobile:
    name: FishSense Mobile
    latex: project_fs_mobile
    branch: fs_mobile
    assignees:
      - ccrutchf
  fs_scout:
    name: FishSense Scout
    latex: project_fs_scout
    branch: fs_scout
    assignees:
      - ccrutchf
  fs_rnd:
    name: FishSense RnD
    latex: project_fs_rnd
    branch: fs_rnd
    assignees:
      - ccrutchf
      - zhenchenglin
  act_learn:
    name: Active Learning
    latex: project_act_learn
    branch: act_learn
    assignees:
      - ccrutchf
      - Sean1572
      - mathslayer-compe #Akhil Nallacheruvu
  radio_telemetry_tracker:
    name: Radio Telemetry Tracker
    latex: project_rtt
    branch: radio_telemetry_tracker
    assignees:
      - vaibhavmaloo03
      - kirustar14
  
  smartfin:
    name: Smartfin
    latex: project_sf
    branch: smartfin
    assignees:
      - stevegtaylor

  website:
    name: Website
    latex: project_web
    branch: web
    assignees:
      - Sean1572
schedule:
  # Keyed by Date of presentation
  "2025-10-06T09:30-07:00": # Week 2
    - acoustic_species_id
    - radio_telemetry_tracker
    - mangrove_monitoring
  "2025-10-13T09:30-07:00": # Week 3
    - fs
    - smartfin
    - act_learn
  "2025-10-20T09:30-07:00": # Week 4
    - radio_telemetry_tracker
    - mangrove_monitoring
    - acoustic_species_id
    - acoustic_collar
  "2025-10-27T09:30-07:00": # Week 5
    - smartfin
    - fs_lite
    - fs_mobile
    - fs_scout
    - fs_rnd
    - act_learn
  "2025-11-03T09:30-07:00": # Week 6
    - mangrove_monitoring
    - acoustic_species_id
    - acoustic_collar
    - radio_telemetry_tracker
  "2025-11-10T09:30-08:00": # Week 7
    - fs_lite
    - fs_mobile
    - fs_scout
    - fs_rnd
    - act_learn
    - smartfin
  "2025-11-17T09:30-08:00": # Week 8
    - acoustic_species_id
    - acoustic_collar
    - radio_telemetry_tracker
    - mangrove_monitoring
  "2025-11-24T09:30-08:00": # Week 9
    - act_learn
    - smartfin
    - fs_lite
    - fs_mobile
    - fs_scout
    - fs_rnd
