projects:
  RobustSciML:
    name: RobustSciML
    latex: project_rsm
    branch: robustsciml
    assignees:
      -
  volt:
    name: Vehicle for Observing Lagrangian Transport
    latex: project_volt
    branch: volt
    assignees:
      -
  mangrove_monitoring:
    name: Mangrove Monitoring
    latex: project_mm
    branch: mangrove_monitoring
    assignees:
      # - Jasonnyang
      - zclawr
  acoustic_species_id:
    name: Acoustic Species ID
    latex: project_aid
    branch: acoustic_species_id
    assignees:
      # - Sean1572
      # - sprestrelski
      - Ludwigvsch
      - tqzhang04
  baboons_on_the_move:
    name: Baboons on the Move
    latex: project_bom
    branch: baboons_on_the_move
    assignees:
      # - ccrutchf
      - TylerFlar
  fishsense:
    name: FishSense
    latex: project_fs
    branch: fishsense
    assignees:
      - ccrutchf
      # - falafel72
      # - avikg511
  radio_telemetry_tracker:
    name: Radio Telemetry Tracker
    latex: project_rtt
    branch: radio_telemetry_tracker
    assignees:
      # - TylerFlar
  smartfin:
    name: Smartfin
    latex: project_sf
    branch: smartfin
    assignees:
      # - ntlhui
  # hardware:
  #   name: Hardware Development Group
  #   latex: project_hw
  #   branch: hardware
  #   assignees:
  #     - ntlhui
  # website:
  #   name: Website
  #   latex: project_web
  #   branch: web
  #   assignees:
  #     - ntlhui
  #     - Sean1572
schedule:
  # Keyed by Date of presentation
  "2024-07-02T09:30-07:00": [
      fishsense,
      radio_telemetry_tracker,
      mangrove_monitoring,
      acoustic_species_id,
      baboons_on_the_move,
      smartfin,
      volt,
    ] # SU24 1
  "2024-07-09T09:30-07:00": [fishsense, radio_telemetry_tracker, smartfin] # SU24 2
  "2024-07-16T09:30-07:00": [
      mangrove_monitoring,
      acoustic_species_id,
      baboons_on_the_move,
    ] # SU24 3
  "2024-07-23T09:30-07:00": [fishsense, radio_telemetry_tracker, smartfin] # SU24 4
  "2024-07-30T09:30-07:00": [
      mangrove_monitoring,
      acoustic_species_id,
      baboons_on_the_move,
    ] # SU24 5
  "2024-08-06T09:30-07:00": [fishsense, radio_telemetry_tracker, smartfin] # SU24 6
  "2024-08-13T09:30-07:00": [
      mangrove_monitoring,
      acoustic_species_id,
      baboons_on_the_move,
    ] # SU24 7
  "2024-08-20T09:30-07:00": [fishsense, radio_telemetry_tracker, smartfin] # SU24 8
  "2024-08-27T09:30-07:00": [mangrove_monitoring, acoustic_species_id] # SU24 9
