projects:
  # maya_vr:
  #   name: Maya VR
  #   latex: project_maya
  #   branch: maya_vr
  #   assignees:
  #     - AviralAgrwal
  mangrove_monitoring:
    name: Mangrove Monitoring
    latex: project_mm
    branch: mangrove_monitoring
    assignees:
      - gagewrye
  acoustic_species_id:
    name: Acoustic Species ID
    latex: project_aid
    branch: acoustic_species_id
    assignees:
      - Sean1572
      # - Ludwigvsch
      # - tqzhang04
  # baboons_on_the_move:
  #   name: Baboons on the Move
  #   latex: project_bom
  #   branch: baboons_on_the_move
  #   assignees:
  #     # - ccrutchf
  #     - TylerFlar
  # a3d_eng:
  #   name: Aqua3D Engineering
  #   latex: project_a3d_eng
  #   branch: a3d_eng
  #   assignees:
  #     - ccrutchf
  #     - avikg511
  fs_core:
    name: FishSense Core
    latex: project_fs_core
    branch: fs_core
    assignees:
      - ccrutchf
      # - bmccalmon
  # act_learn:
  #   name: Active Learning
  #   latex: project_act_learn
  #   branch: act_learn
  #   assignees:
  #     - ccrutchf
  #     - Sean1572
  #     - WesleyJWu
  #     - mathslayer-compe #Akhil Nallacheruvu
  fs_user:
    name: FishSense User
    latex: project_fs_user
    branch: fs_user
    assignees:
      - ccrutchf
  # radio_telemetry_tracker:
  #   name: Radio Telemetry Tracker
  #   latex: project_rtt
  #   branch: radio_telemetry_tracker
  #   assignees:
  #     - TylerFlar
  smartfin:
    name: Smartfin
    latex: project_sf
    branch: smartfin
    assignees:
  website:
    name: Website
    latex: project_web
    branch: web
    assignees:
      - Sean1572
schedule:
  # Keyed by Date of presentation
  "2025-07-01T10:30-07:00": # Week 1
    - fs_core
    - fs_user
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2025-07-08T10:30-07:00": # Week 2
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2025-07-15T10:30-07:00": # Week 3
    - fs_core
    - fs_user
  "2025-07-22T10:30-07:00": # Week 4
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2025-07-29T10:30-07:00": # Week 5
    - fs_core
    - fs_user
  "2025-08-05T10:30-07:00": # Week 6
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
    - maya_vr
  "2025-08-12T10:30-07:00": # Week 7
    - fs_core
    - fs_user
  "2025-08-19T10:30-07:00": [] # Week 8
  "2025-08-26T10:30-07:00": # Week 9

