projects:
  mangrove_monitoring:
    name: Mangrove Monitoring
    latex: project_mm
    branch: mangrove_monitoring
    assignees:
      # - Jasonnyang
      - zclawr
      - gagewrye
  acoustic_species_id:
    name: Acoustic Species ID
    latex: project_aid
    branch: acoustic_species_id
    assignees:
      - Sean1572
      - Ludwigvsch
      - tqzhang04
  baboons_on_the_move:
    name: Baboons on the Move
    latex: project_bom
    branch: baboons_on_the_move
    assignees:
      # - ccrutchf
      - TylerFlar
  fishsense:
    name: FishSense
    latex: project_fs
    branch: fishsense
    assignees:
      - ccrutchf
      - AelizBiz
      - avikg511
  radio_telemetry_tracker:
    name: Radio Telemetry Tracker
    latex: project_rtt
    branch: radio_telemetry_tracker
    assignees:
      - TylerFlar
  smartfin:
    name: Smartfin
    latex: project_sf
    branch: smartfin
    assignees:
      - ntlhui
  website:
    name: Website
    latex: project_web
    branch: web
    assignees:
      - ntlhui
      - Sean1572
schedule:
  # Keyed by Date of presentation
  "2024-09-30T12:00-07:00": # FA24 1
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
    - radio_telemetry_tracker
    - baboons_on_the_move
    - fishsense
  "2024-10-07T12:00-07:00": # FA24 2
    - radio_telemetry_tracker
    - baboons_on_the_move
    - fishsense
  "2024-10-14T12:00-07:00": # FA24 3
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2024-10-21T12:00-07:00": # FA24 4
    - baboons_on_the_move
    - fishsense
    - radio_telemetry_tracker
  "2024-10-28T12:00-07:00": # FA24 5
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2024-11-04T12:00-08:00": # FA24 6
    - baboons_on_the_move
    - fishsense
    - radio_telemetry_tracker
  "2024-11-14T12:00-08:00": # FA24 7
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2024-11-18T12:00-08:00": # FA24 8
    - baboons_on_the_move
    - fishsense
    - radio_telemetry_tracker
  "2024-11-25T12:00-08:00": # FA24 9
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2024-12-02T12:00-08:00": # FA24 10
    - baboons_on_the_move
    - fishsense
    - radio_telemetry_tracker
