projects:
  mangrove_monitoring:
    name: Mangrove Monitoring
    latex: project_mm
    branch: mangrove_monitoring
    assignees:
      - Jasonnyang
      - zclawr
      # 199/299
      - HughieH
  acoustic_species_id:
    name: Acoustic Species ID
    latex: project_aid
    branch: acoustic_species_id
    assignees:
      - Sean1572
      - sprestrelski
      # 199/299
      - JacobGlennAyers
      - Ludwigvsch
  baboons_on_the_move:
    name: Baboons on the Move
    latex: project_bom
    branch: baboons_on_the_move
    assignees:
      - ccrutchf
      - TylerFlar
  fishsense:
    name: FishSense
    latex: project_fs
    branch: fishsense
    assignees:
      - ccrutchf
      - falafel72
      - avikg511
      # 199/299
      - lvking123
  radio_telemetry_tracker:
    name: Radio Telemetry Tracker
    latex: project_rtt
    branch: radio_telemetry_tracker
    assignees:
      - TylerFlar
  smartfin:
    name: Smartfin
    latex: project_sf
    branch: smartfin
    assignees:
      - ntlhui
  hardware:
    name: Hardware Development Group
    latex: project_hw
    branch: hardware
    assignees:
      - ntlhui
  website:
    name: Website
    latex: project_web
    branch: web
    assignees:
      - ntlhui
      - Sean1572
schedule:
  # Keyed by Date of presentation
  '2024-04-01T14:00-07:00': [smartfin, hardware] # SP24 1
  '2024-04-08T14:00-07:00': [fishsense, radio_telemetry_tracker, smartfin, website] # SP24 2
  '2024-04-12T14:00-07:00': [mangrove_monitoring, acoustic_species_id, baboons_on_the_move, website] # SP24 3
  '2024-04-22T14:00-07:00': [fishsense, radio_telemetry_tracker, smartfin, website] # SP24 4
  '2024-04-29T14:00-07:00': [mangrove_monitoring, acoustic_species_id, baboons_on_the_move, website] # SP24 5
  '2024-05-06T14:00-07:00': [fishsense, radio_telemetry_tracker, smartfin, website] # SP24 6
  '2024-05-13T14:00-07:00': [mangrove_monitoring, acoustic_species_id, baboons_on_the_move, website] # SP24 7
  '2024-05-24T11:00-07:00': [fishsense, radio_telemetry_tracker, smartfin, website] # SP24 8
  '2024-05-31T11:00-07:00': [mangrove_monitoring, acoustic_species_id, website] # SP24 9
