projects:
  maya_vr:
    name: Maya VR
    latex: project_maya
    branch: maya_vr
    assignees:
      - AviralAgrwal
  mangrove_monitoring:
    name: Mangrove Monitoring
    latex: project_mm
    branch: mangrove_monitoring
    assignees:
      - Jasonnyang
      - zclawr
      - gagewrye
  acoustic_species_id:
    name: Acoustic Species ID
    latex: project_aid
    branch: acoustic_species_id
    assignees:
      - Sean1572
      - Ludwigvsch
      - tqzhang04
  baboons_on_the_move:
    name: Baboons on the Move
    latex: project_bom
    branch: baboons_on_the_move
    assignees:
      # - ccrutchf
      - TylerFlar
  # a3d_eng:
  #   name: Aqua3D Engineering
  #   latex: project_a3d_eng
  #   branch: a3d_eng
  #   assignees:
  #     - ccrutchf
  #     - avikg511
  fs_core:
    name: FishSense Core
    latex: project_fs_core
    branch: fs_core
    assignees:
      - ccrutchf
      - bmccalmon
  act_learn:
    name: Active Learning
    latex: project_act_learn
    branch: act_learn
    assignees:
      - ccrutchf
      - Sean1572
      - WesleyJWu
      - mathslayer-compe #Akhil Nallacheruvu
  fs_user:
    name: FishSense User
    latex: project_fs_user
    branch: fs_user
    assignees:
      - ccrutchf
      - hnvultimate123
      - Kylehtran
  radio_telemetry_tracker:
    name: Radio Telemetry Tracker
    latex: project_rtt
    branch: radio_telemetry_tracker
    assignees:
      - TylerFlar
  smartfin:
    name: Smartfin
    latex: project_sf
    branch: smartfin
    assignees:
      - ntlhui
  website:
    name: Website
    latex: project_web
    branch: web
    assignees:
      - ntlhui
      - Sean1572
schedule:
  # Keyed by Date of presentation
  "2025-03-31T10:30-07:00": # SP25 1
    - baboons_on_the_move
    - a3d_eng
    - fs_core
    - fs_user
    - radio_telemetry_tracker
    - maya_vr
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2025-04-07T10:30-07:00": # SP25 2
    - maya_vr
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2025-04-14T10:30-07:00": # SP25 3
    - baboons_on_the_move
    - a3d_eng
    - fs_core
    - fs_user
    - radio_telemetry_tracker
  "2025-04-21T10:30-07:00": # SP25 4
    - maya_vr
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2025-04-28T10:30-07:00": # WI25 5
    - baboons_on_the_move
    - a3d_eng
    - fs_core
    - fs_user
    - radio_telemetry_tracker
  "2025-05-05T10:30-07:00": # WI25 6
    - maya_vr
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2025-05-12T10:30-07:00": # WI25 7
    - baboons_on_the_move
    - a3d_eng
    - fs_core
    - fs_user
    - radio_telemetry_tracker
  "2025-05-19T10:30-08:00": # SP25 8
    - maya_vr
    - mangrove_monitoring
    - acoustic_species_id
    - smartfin
  "2025-06-09T10:30-07:00": [] # SP25 10 199/299
