projects:
  mangrove_monitoring:
    name: Mangrove Monitoring
    latex: project_mm
    branch: mangrove_monitoring
    assignees:
      - Jasonnyang
  acoustic_species_id:
    name: Acoustic Species ID
    latex: project_aid
    branch: acoustic_species_id
    assignees:
      - Sean1572
      - sprestrelski
  baboons_on_the_move:
    name: Baboons on the Move
    latex: project_bom
    branch: baboons_on_the_move
    assignees:
      - ccrutchf
      - TylerFlar
  fishsense:
    name: FishSense
    latex: project_fs
    branch: fishsense
    assignees:
      - ccrutchf
      - falafel72
  radio_telemetry_tracker:
    name: Radio Telemetry Tracker
    latex: project_rtt
    branch: radio_telemetry_tracker
    assignees:
      - TylerFlar
  smartfin:
    name: Smartfin
    latex: project_sf
    branch: smartfin
    assignees:
      - ntlhui
  hardware:
    name: Hardware Development Group
    latex: project_hw
    branch: hardware
    assignees:
      - ntlhui
schedule:
  # Keyed by ISO Week Number of presentation
  '2024-01-10': [smartfin, hardware]
  '2024-01-17': [mangrove_monitoring, acoustic_species_id, baboons_on_the_move] # WI24 2
  '2024-01-24': [fishsense, radio_telemetry_tracker, smartfin] # WI24 3
  '2024-01-31': [mangrove_monitoring, acoustic_species_id, baboons_on_the_move] # WI24 4
  '2024-02-07': [fishsense, radio_telemetry_tracker, smartfin] # WI24 5
  '2024-02-14': [mangrove_monitoring, acoustic_species_id, baboons_on_the_move] # WI24 6
  '2024-02-21': [fishsense, radio_telemetry_tracker, smartfin] # WI24 7
  '2024-02-28': [mangrove_monitoring, acoustic_species_id, baboons_on_the_move] # WI24 8
  '2024-03-06': [fishsense, radio_telemetry_tracker, smartfin] # WI24 9