projects:
  # maya_vr:
  #   name: Maya VR
  #   latex: project_maya
  #   branch: maya_vr
  #   assignees:
  #     - AviralAgrwal
  mangrove_monitoring:
    name: Mangrove Monitoring
    latex: project_mm
    branch: mangrove_monitoring
    assignees:
      - gagewrye
      - TWintersww
  acoustic_species_id:
    name: Acoustic Species ID
    latex: project_aid
    branch: acoustic_species_id
    assignees:
      - Sean1572
      - SiyaKamboj
      - Ludwigvsch
      - tqzhang04
  baboons_on_the_move:
    name: Baboons on the Move
    latex: project_bom
    branch: baboons_on_the_move
    assignees:
      # - ccrutchf
      - TylerFlar
  # a3d_eng:
  #   name: Aqua3D Engineering
  #   latex: project_a3d_eng
  #   branch: a3d_eng
  #   assignees:
  #     - ccrutchf
  #     - avikg511
  fs:
    name: FishSense
    latex: project_fs
    branch: fs
    assignees:
      - ccrutchf
      - Shuzhengz
      - Nykolas1100
      - aayushkananu
      - annabchen 
      - tdarcima
      - shrsijan
      - brendonamw  
      # - bmccalmon
  act_learn:
    name: Active Learning
    latex: project_act_learn
    branch: act_learn
    assignees:
      - ccrutchf
      - Sean1572
      - WesleyJWu
      - mathslayer-compe #Akhil Nallacheruvu
  radio_telemetry_tracker:
    name: Radio Telemetry Tracker
    latex: project_rtt
    branch: radio_telemetry_tracker
    assignees:
      - TylerFlar
  
  smartfin:
    name: Smartfin
    latex: project_sf
    branch: smartfin
    assignees:
      - aayushkananu 
      - ntlhui

  website:
    name: Website
    latex: project_web
    branch: web
    assignees:
      - Sean1572
schedule:
  # Keyed by Date of presentation
  "2025-10-06T09:30-07:00": # Week 2
    - acoustic_species_id
    - radio_telemetry_tracker
    - mangrove_monitoring
  "2025-10-13T09:30-07:00": # Week 3
    - fs
    - smartfin
    - act_learn
  "2025-10-20T09:30-07:00": # Week 4
    - radio_telemetry_tracker
    - mangrove_monitoring
    - acoustic_species_id
  "2025-10-27T09:30-07:00": # Week 5
    - smartfin
    - fs 
    - act_learn
  "2025-11-03T09:30-07:00": # Week 6
    - mangrove_monitoring
    - acoustic_species_id
    - radio_telemetry_tracker
  "2025-11-10T09:30-07:00": # Week 7
    - fs
    - act_learn
    - smartfin
  "2025-11-17T09:30-07:00": # Week 8
    - acoustic_species_id
    - radio_telemetry_tracker
    - mangrove_monitoring
  "2025-11-24T09:30-07:00": # Week 9
    - act_learn
    - smartfin
    - fs
