name: Create Project Branches

on:
  schedule:
    - cron: '0 9 * * 4'
  workflow_dispatch:

jobs:
  create_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Los_Angeles"
          timezoneMacos: "America/Los_Angeles"
          timezoneWindows: "Pacific Standard Time"
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Set up Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt
      - name: Create Branches
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          python configure_presentation.py
          