name: Create Project Branches

on:
  push:
    branches:
      - main
    paths:
      - 'config.yml' # Replace with the actual file path
  schedule:
    - cron: '30 04 14 10 *' # Executes at 2025-10-13T21:30:00-07:00
  workflow_dispatch:

permissions:
  actions:
    write
  contents: write
  
jobs:
  create_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASER }}
      - name: Set Timezone
        uses: MathRobin/timezone-action@v1.1
        with:
          timezoneLinux: "America/Los_Angeles"
          timezoneMacos: "America/Los_Angeles"
          timezoneWindows: "Pacific Standard Time"
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt
      - name: Create Branches
        env:
          GH_TOKEN: ${{ secrets.RELEASER }}
        run: |
          python configure_presentation.py
          
