name: Weekly Build

on:
  schedule:
    - cron: '00 16 20 10 *' # Executes at 2025-10-20T09:00:00-07:00
  workflow_dispatch: 
  push: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Los_Angeles"
          timezoneMacos: "America/Los_Angeles"
          timezoneWindows: "Pacific Standard Time"
      - name: LaTeX Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: presentation.tex
      - name: Create Upload Artifact
        run: |
          cp presentation.pdf `date +e4e_weekly_presentation_%Y-%m-%dT%H-%M-%S.pdf`
          mkdir out
          cp presentation.pdf out/e4e_weekly_presentation.pdf
          ls -al
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: e4e_weekly_presentation*
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          clean: true
          single-commit: true
          folder: out
          git-config-name: e4e_github_actions
          git-config-email: e4e@ucsd.edu
      - name: Prepare Release Parameters
        run: |
          TZ='America/Los_Angeles'
          echo "today_date=$(date -I)" >> $GITHUB_ENV
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        if: ${{ github.event_name == 'schedule' && github.ref == 'refs/heads/main' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.today_date }}
          prerelease: false
          files: e4e_weekly_presentation*
