name: Weekly Build

on:
  schedule:
    - cron: '30 14 * * 3'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: LaTeX Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: presentation.tex
      - name: Create Upload Artifact
        run: |
          cp presentation.pdf `date +e4e_weekly_presentation_%Y-%m-%dT%H-%M-%S.pdf`
          mkdir out
          cp presentation.pdf out/e4e_weekly_presentation.pdf
          ls -al
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: e4e_weekly_presentation*
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          clean: true
          single-commit: true
          folder: out
          git-config-name: e4e_github_actions
          git-config-email: e4e@ucsd.edu
